### ISSUE TITLE
Danbooru batch download not working

### ISSUE THREAD

**Issue by Argusian** [Nandaka/DanbooruDownloader#128]
Since yesterday, I get the following error whenever I try a batch download on Danbooru:

` [DoBatchJob] Error Getting List (1 of 5): The operation has timed out Wait for 120s.
System.Net.WebException: The operation has timed out
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at DanbooruDownloader3.FormMain.GetBatchImageList(String url, String query, DanbooruBatchJob job)`

However, searches and downloads works fine on both my browser and the single picture mode of DanbooruDownloader.

It was working fine until yesterday and I didn't fiddle with my settings in a long while.

**Comment by Argusian** [comment]
Additionally, some pictures fail to download and generate the following error message:

`Error Resolving FileUrl (1 of 5): Object reference not set to an instance of an object. Wait for 60s.
System.NullReferenceException: Object reference not set to an instance of an object.
   at DanbooruDownloader3.Engine.SankakuComplexParser.ReparseTags(DanbooruPost post, HtmlDocument doc)
   at DanbooruDownloader3.Engine.SankakuComplexParser.ParsePost(DanbooruPost post, String postHtml, Boolean overideTagParsing)
   at DanbooruDownloader3.FormMain.ResolveFileUrlBatch(ExtendedWebClient _clientPost, DanbooruPost post)
`

**Comment by Nandaka** [comment]
Looks like they changing something on the api, also they now block those loli/shota stuff unless you got gold account. I recommend you to use gelbooru for time being.

**Comment by Nandaka** [comment]
Try https://github.com/Nandaka/DanbooruDownloader/releases/tag/v3.20170808

it should skip the files if no urls detected.
