### ISSUE TITLE
Sankaku Download Error

### ISSUE THREAD

**Issue by random1-coder** [Nandaka/DanbooruDownloader#236]
Whenever I try to download via full batch mode or download list, this warning always comes out and the download is canceled.

[DoBatchJob] Error: Length cannot be less than zero.
Parameter name: length
Stack Trace: 
   at System.String.Substring(Int32 startIndex, Int32 length)
   at DanbooruDownloader3.Helper.MakeFilename(DanbooruFilenameFormat format, DanbooruPost post)
   at DanbooruDownloader3.FormMain.MakeCompleteFilename(DanbooruPost post, String url, String filenameFormat)
   at DanbooruDownloader3.FormMain.ProcessBatchJobPost(DanbooruBatchJob currentJob, UpdateUiDelegate del, ExtendedWebClient _clientPost, Int32& imgCount, Int32& skipCount, DanbooruPost post)
   at DanbooruDownloader3.FormMain.DoBatchJob(BindingList`1 batchJob)

**Comment by Nandaka** [comment]
looks like sankaku changes the layout again. not sure when I can fix this.

**Comment by Nandaka** [comment]
Looks like due to cookie handling, try to remove the extra `;`
![image](https://user-images.githubusercontent.com/836867/115945072-5b8aeb00-a4ec-11eb-94eb-b59f72bfbb82.png)
![image](https://user-images.githubusercontent.com/836867/115945185-13b89380-a4ed-11eb-8d55-065e4edb2c9e.png)

You can verify if the cookies loaded correctly by selecting the provider and then click the `Cookie` button in the settings tab:
![image](https://user-images.githubusercontent.com/836867/115945216-36e34300-a4ed-11eb-8ca4-8f40131117d7.png)

**Comment by random1-coder** [comment]
It looks like something happened and the url failed to fetch

![Untitled](https://user-images.githubusercontent.com/83064214/115948928-584b2b80-a4fb-11eb-91a7-a6c2b673014b.png)

**Comment by Nandaka** [comment]
url only resolved after you add the to the download list.

**Comment by random1-coder** [comment]
Error warning 'Error: Length cannot be less than zero.' (the issue) appeared and only the first list gets the url. The rest, it's just loading forever.
![Untitled](https://user-images.githubusercontent.com/83064214/115950691-001a2680-a507-11eb-95ca-91a3d8b55350.png)

**Comment by Nandaka** [comment]
you are using latest version? remember to update the cookie values. If you are not logged in, then you cannot download the full image anymore for sankaku (pls check the readme).

**Comment by random1-coder** [comment]
I am logged in and the error is still there. A bunch blank url and skipped file for batch download. Loading forever for the download list. Is the program working well on your side?
![Untitled](https://user-images.githubusercontent.com/83064214/115952412-e7623e80-a50f-11eb-9c5b-5c81002ff5b1.png)

**Comment by Nandaka** [comment]
Looks good on my side:
![image](https://user-images.githubusercontent.com/836867/115956165-daecde80-a52d-11eb-9374-4997153409e3.png)

**Comment by Shirkit** [comment]
I am having the same exact issue, even though I think I have setup correctly using the login cookie method. The Cookie Viwer screen for some reason also duplicates the content of the cookie, even though I have only pasted it once.

It fails to resolve and download any images from Sankaku at all, it skips all the images, regardless of extreme content or logged in.

`2021-04-24 09:53:32,361 INFO  - [DoBatchJob] Getting file_url from https://chan.sankakucomplex.com/post/show/20562262
2021-04-24 09:53:33,064 INFO  - [DoBatchJob] File Url: 
2021-04-24 09:53:33,126 INFO  - [DoBatchJob] Download skipped, ID: 20562262 No file_url, probably deleted
2021-04-24 09:53:33,164 INFO  - [DoBatchJob] Getting file_url from https://chan.sankakucomplex.com/post/show/21537533
2021-04-24 09:53:33,968 INFO  - [DoBatchJob] File Url: 
2021-04-24 09:53:34,031 INFO  - [DoBatchJob] Download skipped, ID: 21537533 No file_url, probably deleted
2021-04-24 09:53:34,068 INFO  - [DoBatchJob] Getting file_url from https://chan.sankakucomplex.com/post/show/22468865
2021-04-24 09:53:34,686 INFO  - [DoBatchJob] File Url: 
2021-04-24 09:53:34,739 INFO  - [DoBatchJob] Download skipped, ID: 22468865 No file_url, probably deleted
2021-04-24 09:53:34,786 INFO  - [DoBatchJob] Getting file_url from https://chan.sankakucomplex.com/post/show/24763345
2021-04-24 09:53:35,388 INFO  - [DoBatchJob] File Url: 
2021-04-24 09:53:35,441 INFO  - [DoBatchJob] Download skipped, ID: 24763345 No file_url, probably deleted
2021-04-24 09:53:35,488 INFO  - [DoBatchJob] Getting file_url from https://chan.sankakucomplex.com/post/show/24894559
2021-04-24 09:53:35,921 INFO  - [DoBatchJob] File Url: 
2021-04-24 09:53:35,974 INFO  - [DoBatchJob] Download skipped, ID: 24894559 No file_url, probably deleted
2021-04-24 09:53:36,021 INFO  - [DoBatchJob] Getting file_url from https://chan.sankakucomplex.com/post/show/20498401
2021-04-24 09:53:36,810 INFO  - [DoBatchJob] File Url: 
2021-04-24 09:53:36,863 INFO  - [DoBatchJob] Download skipped, ID: 20498401 No file_url, probably deleted
2021-04-24 09:53:36,910 INFO  - [DoBatchJob] Getting file_url from https://chan.sankakucomplex.com/post/show/21143324
2021-04-24 09:53:37,681 INFO  - [DoBatchJob] File Url: 
2021-04-24 09:53:37,743 INFO  - [DoBatchJob] Download skipped, ID: 21143324 No file_url, probably deleted
2021-04-24 09:53:37,781 INFO  - [DoBatchJob] Getting file_url from https://chan.sankakucomplex.com/post/show/20902392
2021-04-24 09:53:38,384 INFO  - [DoBatchJob] File Url: 
2021-04-24 09:53:38,431 INFO  - [DoBatchJob] Download skipped, ID: 20902392 No file_url, probably deleted
2021-04-24 09:53:38,484 INFO  - [DoBatchJob] Getting file_url from https://chan.sankakucomplex.com/post/show/20909074
2021-04-24 09:53:39,457 INFO  - [DoBatchJob] File Url: 
2021-04-24 09:53:39,504 INFO  - [DoBatchJob] Download skipped, ID: 20909074 No file_url, probably deleted
2021-04-24 09:53:39,557 INFO  - [DoBatchJob] Getting file_url from https://chan.sankakucomplex.com/post/show/21153363
2021-04-24 09:53:40,137 INFO  - [DoBatchJob] File Url: 
2021-04-24 09:53:40,190 INFO  - [DoBatchJob] Download skipped, ID: 21153363 No file_url, probably deleted
2021-04-24 09:53:40,237 INFO  - [DoBatchJob] Getting file_url from https://chan.sankakucomplex.com/post/show/21182032
2021-04-24 09:53:40,939 INFO  - [DoBatchJob] File Url: 
2021-04-24 09:53:41,008 INFO  - [DoBatchJob] Download skipped, ID: 21182032 No file_url, probably deleted
2021-04-24 09:53:41,054 INFO  - [DoBatchJob] Getting file_url from https://chan.sankakucomplex.com/post/show/24875081
2021-04-24 09:53:41,858 INFO  - [DoBatchJob] File Url: 
2021-04-24 09:53:41,911 INFO  - [DoBatchJob] Download skipped, ID: 24875081 No file_url, probably deleted
2021-04-24 09:53:41,958 INFO  - [DoBatchJob] Getting file_url from https://chan.sankakucomplex.com/post/show/24850179
2021-04-24 09:53:42,861 INFO  - [DoBatchJob] File Url: 
2021-04-24 09:53:42,899 INFO  - [DoBatchJob] Download skipped, ID: 24850179 No file_url, probably deleted
2021-04-24 09:53:42,962 INFO  - [DoBatchJob] Getting file_url from https://chan.sankakucomplex.com/post/show/20785933
2021-04-24 09:53:43,547 INFO  - [DoBatchJob] File Url: 
2021-04-24 09:53:43,585 INFO  - [DoBatchJob] Download skipped, ID: 20785933 No file_url, probably deleted
2021-04-24 09:53:43,647 INFO  - [DoBatchJob] Getting file_url from https://chan.sankakucomplex.com/post/show/1555542
2021-04-24 09:53:44,087 INFO  - [DoBatchJob] File Url: 
2021-04-24 09:53:44,134 INFO  - [DoBatchJob] Download skipped, ID: 1555542 No file_url, probably deleted
2021-04-24 09:53:44,172 INFO  - [DoBatchJob] Getting file_url from https://chan.sankakucomplex.com/post/show/3732735
2021-04-24 09:53:44,589 INFO  - [DoBatchJob] File Url: 
2021-04-24 09:53:44,635 INFO  - [DoBatchJob] Download skipped, ID: 3732735 No file_url, probably deleted
2021-04-24 09:53:44,689 INFO  - [DoBatchJob] Getting file_url from https://chan.sankakucomplex.com/post/show/5066653
2021-04-24 09:53:45,137 INFO  - [DoBatchJob] File Url: 
2021-04-24 09:53:45,190 INFO  - [DoBatchJob] Download skipped, ID: 5066653 No file_url, probably deleted
2021-04-24 09:53:45,237 INFO  - [DoBatchJob] Getting file_url from https://chan.sankakucomplex.com/post/show/7769223
2021-04-24 09:53:45,870 INFO  - [DoBatchJob] File Url: 
2021-04-24 09:53:45,908 INFO  - [DoBatchJob] Download skipped, ID: 7769223 No file_url, probably deleted
2021-04-24 09:53:45,970 INFO  - [DoBatchJob] Getting file_url from https://chan.sankakucomplex.com/post/show/5908327
2021-04-24 09:53:46,394 INFO  - [DoBatchJob] File Url: 
2021-04-24 09:53:46,441 INFO  - [DoBatchJob] Download skipped, ID: 5908327 No file_url, probably deleted
2021-04-24 09:53:46,479 INFO  - [DoBatchJob] Getting file_url from https://chan.sankakucomplex.com/post/show/1658896
2021-04-24 09:53:46,911 INFO  - [DoBatchJob] File Url: 
2021-04-24 09:53:46,974 INFO  - [DoBatchJob] Download skipped, ID: 1658896 No file_url, probably deleted
2021-04-24 09:53:47,096 INFO  - [DoBatchJob] Downloading list: https://chan.sankakucomplex.com/?tags=fav:klajwo1&page=2
2021-04-24 09:53:49,403 INFO  - [DoBatchJob] Getting file_url from https://chan.sankakucomplex.com/post/show/1682558
2021-04-24 09:53:50,149 INFO  - [DoBatchJob] File Url: 
2021-04-24 09:53:50,202 INFO  - [DoBatchJob] Download skipped, ID: 1682558 No file_url, probably deleted
2021-04-24 09:53:50,249 INFO  - [DoBatchJob] Getting file_url from https://chan.sankakucomplex.com/post/show/5931799
2021-04-24 09:53:50,850 INFO  - [DoBatchJob] File Url: 
2021-04-24 09:53:50,904 INFO  - [DoBatchJob] Download skipped, ID: 5931799 No file_url, probably deleted
2021-04-24 09:53:50,951 INFO  - [DoBatchJob] Getting file_url from https://chan.sankakucomplex.com/post/show/1427376
2021-04-24 09:53:51,405 INFO  - [DoBatchJob] File Url: 
2021-04-24 09:53:51,452 INFO  - [DoBatchJob] Download skipped, ID: 1427376 No file_url, probably deleted
2021-04-24 09:53:51,490 INFO  - [DoBatchJob] Getting file_url from https://chan.sankakucomplex.com/post/show/5118279
2021-04-24 09:53:52,223 INFO  - [DoBatchJob] File Url: 
2021-04-24 09:53:52,270 INFO  - [DoBatchJob] Download skipped, ID: 5118279 No file_url, probably deleted
2021-04-24 09:53:52,324 INFO  - [DoBatchJob] Getting file_url from https://chan.sankakucomplex.com/post/show/629723
2021-04-24 09:53:53,042 INFO  - [DoBatchJob] File Url: 
2021-04-24 09:53:53,095 INFO  - [DoBatchJob] Download skipped, ID: 629723 No file_url, probably deleted
2021-04-24 09:53:53,158 INFO  - [DoBatchJob] Getting file_url from https://chan.sankakucomplex.com/post/show/1740290
2021-04-24 09:53:53,812 INFO  - [DoBatchJob] File Url: 
2021-04-24 09:53:53,859 INFO  - [DoBatchJob] Download skipped, ID: 1740290 No file_url, probably deleted
2021-04-24 09:53:53,897 INFO  - [DoBatchJob] Getting file_url from https://chan.sankakucomplex.com/post/show/4002013
2021-04-24 09:53:54,861 INFO  - [DoBatchJob] File Url: 
2021-04-24 09:53:54,915 INFO  - [DoBatchJob] Download skipped, ID: 4002013 No file_url, probably deleted
2021-04-24 09:53:54,961 INFO  - [DoBatchJob] Getting file_url from https://chan.sankakucomplex.com/post/show/7715062
2021-04-24 09:53:55,732 INFO  - [DoBatchJob] File Url: 
2021-04-24 09:53:55,779 INFO  - [DoBatchJob] Download skipped, ID: 7715062 No file_url, probably deleted
2021-04-24 09:53:55,832 INFO  - [DoBatchJob] Getting file_url from https://chan.sankakucomplex.com/post/show/7798337
2021-04-24 09:53:56,603 INFO  - [DoBatchJob] File Url: 
2021-04-24 09:53:56,649 INFO  - [DoBatchJob] Download skipped, ID: 7798337 No file_url, probably deleted
2021-04-24 09:53:56,703 INFO  - [DoBatchJob] Getting file_url from https://chan.sankakucomplex.com/post/show/25692
2021-04-24 09:53:57,406 INFO  - [DoBatchJob] File Url: 
2021-04-24 09:53:57,468 INFO  - [DoBatchJob] Download skipped, ID: 25692 No file_url, probably deleted
2021-04-24 09:53:57,506 INFO  - [DoBatchJob] Getting file_url from https://chan.sankakucomplex.com/post/show/3786258
2021-04-24 09:53:58,355 INFO  - [DoBatchJob] File Url: 
2021-04-24 09:53:58,386 INFO  - [DoBatchJob] Download skipped, ID: 3786258 No file_url, probably deleted
2021-04-24 09:53:58,424 INFO  - [DoBatchJob] Getting file_url from https://chan.sankakucomplex.com/post/show/3787930
2021-04-24 09:53:59,342 INFO  - [DoBatchJob] File Url: 
2021-04-24 09:53:59,389 INFO  - [DoBatchJob] Download skipped, ID: 3787930 No file_url, probably deleted
2021-04-24 09:53:59,427 INFO  - [DoBatchJob] Getting file_url from https://chan.sankakucomplex.com/post/show/21174339
2021-04-24 09:53:59,875 INFO  - [DoBatchJob] File Url: 
2021-04-24 09:53:59,913 INFO  - [DoBatchJob] Download skipped, ID: 21174339 No file_url, probably deleted
2021-04-24 09:53:59,959 INFO  - [DoBatchJob] Getting file_url from https://chan.sankakucomplex.com/post/show/6357786
2021-04-24 09:54:00,776 INFO  - [DoBatchJob] File Url: 
2021-04-24 09:54:00,814 INFO  - [DoBatchJob] Download skipped, ID: 6357786 No file_url, probably deleted
2021-04-24 09:54:00,861 INFO  - [DoBatchJob] Getting file_url from https://chan.sankakucomplex.com/post/show/6334563
2021-04-24 09:54:01,731 INFO  - [DoBatchJob] File Url: 
2021-04-24 09:54:01,778 INFO  - [DoBatchJob] Download skipped, ID: 6334563 No file_url, probably deleted
2021-04-24 09:54:01,816 INFO  - [DoBatchJob] Getting file_url from https://chan.sankakucomplex.com/post/show/22425811
2021-04-24 09:54:02,432 INFO  - [DoBatchJob] File Url: 
2021-04-24 09:54:02,479 INFO  - [DoBatchJob] Download skipped, ID: 22425811 No file_url, probably deleted
2021-04-24 09:54:02,517 INFO  - [DoBatchJob] Getting file_url from https://chan.sankakucomplex.com/post/show/20432955
2021-04-24 09:54:03,165 INFO  - [DoBatchJob] File Url: 
2021-04-24 09:54:03,212 INFO  - [DoBatchJob] Download skipped, ID: 20432955 No file_url, probably deleted
2021-04-24 09:54:03,249 INFO  - [DoBatchJob] Getting file_url from https://chan.sankakucomplex.com/post/show/20522478
2021-04-24 09:54:04,067 INFO  - [DoBatchJob] File Url: 
2021-04-24 09:54:04,120 INFO  - [DoBatchJob] Download skipped, ID: 20522478 No file_url, probably deleted
2021-04-24 09:54:04,182 INFO  - [DoBatchJob] Getting file_url from https://chan.sankakucomplex.com/post/show/21165612
2021-04-24 09:54:04,821 INFO  - [DoBatchJob] File Url: 
2021-04-24 09:54:04,868 INFO  - [DoBatchJob] Download skipped, ID: 21165612 No file_url, probably deleted
2021-04-24 09:54:04,953 INFO  - [DoBatchJob] Getting file_url from https://chan.sankakucomplex.com/post/show/22434506
2021-04-24 09:54:05,740 INFO  - [DoBatchJob] File Url: 
2021-04-24 09:54:05,787 INFO  - [DoBatchJob] Download skipped, ID: 22434506 No file_url, probably deleted
2021-04-24 09:54:05,903 INFO  - [DoBatchJob] Downloading list: https://chan.sankakucomplex.com/?tags=fav:klajwo1&page=3
2021-04-24 09:54:08,848 INFO  - [DoBatchJob] Getting file_url from https://chan.sankakucomplex.com/post/show/7769017
2021-04-24 09:54:09,717 INFO  - [DoBatchJob] File Url: 
2021-04-24 09:54:09,762 INFO  - [DoBatchJob] Download skipped, ID: 7769017 No file_url, probably deleted
2021-04-24 09:54:09,823 INFO  - [DoBatchJob] Getting file_url from https://chan.sankakucomplex.com/post/show/20705390
2021-04-24 09:54:10,434 INFO  - [DoBatchJob] File Url: 
2021-04-24 09:54:10,493 INFO  - [DoBatchJob] Download skipped, ID: 20705390 No file_url, probably deleted
2021-04-24 09:54:10,542 INFO  - [DoBatchJob] Getting file_url from https://chan.sankakucomplex.com/post/show/21940401
2021-04-24 09:54:10,966 INFO  - [DoBatchJob] File Url: 
2021-04-24 09:54:11,007 INFO  - [DoBatchJob] Download skipped, ID: 21940401 No file_url, probably deleted
2021-04-24 09:54:11,043 INFO  - [DoBatchJob] Getting file_url from https://chan.sankakucomplex.com/post/show/23414278
2021-04-24 09:54:11,931 INFO  - [DoBatchJob] File Url: 
2021-04-24 09:54:11,975 INFO  - [DoBatchJob] Download skipped, ID: 23414278 No file_url, probably deleted
2021-04-24 09:54:12,016 INFO  - [DoBatchJob] Getting file_url from https://chan.sankakucomplex.com/post/show/24371253
2021-04-24 09:54:12,441 INFO  - [DoBatchJob] File Url: 
2021-04-24 09:54:12,486 INFO  - [DoBatchJob] Download skipped, ID: 24371253 No file_url, probably deleted`

`v=0; locale=en; blacklisted_tags=; login=XXXX; pass_hash=XXXXX; _sankakucomplex_session=XXXXX;`


![Sem título](https://user-images.githubusercontent.com/829823/115959471-bb7c9400-a4e2-11eb-9dda-ee26e078b2fe.jpg)
![Sem título2](https://user-images.githubusercontent.com/829823/115959472-bcadc100-a4e2-11eb-9894-2b0e2e568a09.jpg)
![Capturar](https://user-images.githubusercontent.com/829823/115959473-bcadc100-a4e2-11eb-8075-4bee88694029.JPG)

**Comment by Nandaka** [comment]
Are you using the same User Agent with the browser you use to get the cookie values?

**Comment by Shirkit** [comment]
@Nandaka yes, I copied the UserAgent from the request Headers

`Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0`

It skips downloads of all files in Batch mode. Also, on Main, after I do ANY query, and then select an image and press ADD, when I click DOWNLOAD LIST, after 0,5-1second it throws that exception.

![image](https://user-images.githubusercontent.com/829823/115963333-44043000-a4f5-11eb-94e5-52886924039f.png)

**Comment by Nandaka** [comment]
then I have no idea why, because it is working on my side.
![image](https://user-images.githubusercontent.com/836867/115963917-4d70b500-a554-11eb-8cc6-a002e7297008.png)

![image](https://user-images.githubusercontent.com/836867/115963931-5f525800-a554-11eb-9c15-88d9991088fa.png)

**Comment by Shirkit** [comment]
Maybe it's a library issue or a config you have somehow in your local PC?

Maybe try downloading the latest from Github and start fresh to see if it behaves as we are describing.

I've recorded a video showing me trying to use it https://we.tl/t-08raC1tHCQ

**Comment by KoroloSV** [comment]
It seems the issue lies with their host, as the site it self has also been loading very slowly according to the users on their forum, similar programs are also having this issue.
Just wait it out for a few or more days and it might sort it self out.
