### ISSUE TITLE
rule34hentai.net Unhandled exception

### ISSUE THREAD

**Issue by rsaotome2k21** [Nandaka/DanbooruDownloader#256]
The last time rule34hentai.net worked correctly was Dec 9, 2021, but I haven't used the program since then, so I can't state with 100% accuracy when the problem started occurring.

When trying to GET list from Provider: rule34hentai.net, I get the following error:

---------------------------------------------------------------------------------------------------------------------

Unhandled exception has occurred in your application, If you click Continue, the application will ignore this error and attempt to continue. If you click Quick, the application will close immediately.

'doctype' is an unexpected token. The expected token is 'DOCTYPE'.
Line 1, position 3.

************** Exception Text **************
System.Xml.XmlException: 'doctype' is an unexpected token. The expected token is 'DOCTYPE'. Line 1, position 3.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDoctypeDecl()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at DanbooruDownloader3.Engine.ShimmieEngine.ReadRssMethod2(DanbooruPostDaoOption option, BindingList`1 posts, String xmldoc)
   at DanbooruDownloader3.Engine.ShimmieEngine.ParseRSS(String xmldoc, DanbooruPostDaoOption option)
   at DanbooruDownloader3.DAO.DanbooruPostDao.ProcessXML(String rawData)
   at DanbooruDownloader3.DAO.DanbooruPostDao..ctor(Stream input, DanbooruPostDaoOption option, Nullable`1 currentPage)
   at DanbooruDownloader3.FormMain.clientList_DownloadDataCompleted(Object sender, DownloadDataCompletedEventArgs e)
   at System.Net.WebClient.OnDownloadDataCompleted(DownloadDataCompletedEventArgs e)

---------------------------------------------------------------------------------------------------------------------

If you need more info, I can provide it. Since all other Providers seem to be working alright, I can only assume rule34hentai changed something on their end.

I did install the newest build & re-downloaded all xml files, started from scratch, except, I'm not sure where the settings are stored, so I couldn't reset those, hope that helps.

Thank you.

**Comment by Nandaka** [comment]
Yes, looks like the returned page doesn't follow the proper format.
![image](https://user-images.githubusercontent.com/836867/147382277-4e7804d3-a257-4b9f-bd9e-99341893ba35.png)

Also, I notice that they remove the rss link
![image](https://user-images.githubusercontent.com/836867/147382298-c281e9fc-d8a1-41af-a5dc-5fc8bd830b84.png)
