### ISSUE TITLE
Object reference not set to an instance of an object with gelbooru.com

### ISSUE THREAD

**Issue by valdearg** [Nandaka/DanbooruDownloader#258]
Don't suppose anyone has tried downloading from gelbooru lately, I'm getting the following error with it:

```
2022-01-16 13:46:56,501 ERROR - [DoBatchJob] Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at DanbooruDownloader3.FormMain.ProcessBatchJobPost(DanbooruBatchJob currentJob, ExtendedWebClient _clientPost, DanbooruPost post)
   at DanbooruDownloader3.FormMain.ProcessBatchJobPosts(DanbooruPostDao prevDao, DanbooruPostDao d, Boolean& flag, DanbooruBatchJob job, ExtendedWebClient clientPost)
System.NullReferenceException: Object reference not set to an instance of an object.
   at DanbooruDownloader3.FormMain.ProcessBatchJobPost(DanbooruBatchJob currentJob, ExtendedWebClient _clientPost, DanbooruPost post)
   at DanbooruDownloader3.FormMain.ProcessBatchJobPosts(DanbooruPostDao prevDao, DanbooruPostDao d, Boolean& flag, DanbooruBatchJob job, ExtendedWebClient clientPost)
2022-01-16 13:46:56,549 INFO  - [DoBatchJob] Downloading list: https://gelbooru.com/index.php?page=dapi&s=post&q=index&tags=asada_shino&limit=20&pid=21
```

I've been playing around with the cookie login method as per Q7 and screenshot. I can see that Gelbooru gives:

PHPSESSID=<value>; user_id=<value>; pass_hash=<value>

I've tried this in a couple of different formats (user_id + pass_hash, all, etc) but seems to be the same.

![image](https://user-images.githubusercontent.com/2789033/149662958-7526223e-29fb-433c-ad20-24e0e410735e.png)

I presume it's because we don't get anything down in terms of tags maybe?

![image](https://user-images.githubusercontent.com/2789033/149662914-924d9602-444c-4d55-a670-1847888a6c79.png)

Hopefully something dumb I'm doing! Any advice appreciated!

**Comment by Legendsmith** [comment]
I'm experiencing the same thing with gelbooru's API not actually returning any results.

**Comment by KatieWebb** [comment]
I'm having the same issue? Any luck fixing it?

**Comment by Legendsmith** [comment]
This is still occurring as far as I know

**Comment by Nandaka** [comment]
should be fixed in https://github.com/Nandaka/DanbooruDownloader/releases/tag/v3.20220406

for reference
![image](https://user-images.githubusercontent.com/836867/161925982-93155916-c879-4cfa-afa7-65bd98cc86d1.png)
