### ISSUE TITLE
Full Batch Mode doesn't work with Sankaku

### ISSUE THREAD

**Issue by Romangelo** [Nandaka/DanbooruDownloader#268]
v3.20220804

Full Batch Mode, no file can be downloaded. Always skipped.

Log:
[DoBatchJob] Download skipped, ID: 31338817 ==> No file_url, probably deleted
[DoBatchJob] Getting file_url from https://chan.sankakucomplex.com/post/show/31338815
[DoBatchJob] Error Resolving FileUrl (1 of 10): Input string was not in a correct format. ==> Wait for 120s.
[DoBatchJob] Retrying...

Also, I tried to donate to you, but it seems Paypal doesn't accept money from my country. Do you have any other way to accept donation?

**Comment by Nandaka** [comment]
I think you need to add the cookie value in `DanbooruProviderList.xml` for sankaku (check the readme on how to add).
![image](https://user-images.githubusercontent.com/836867/182872227-56b8499b-af79-4706-93ab-3b662e6ae1e6.png)

![image](https://user-images.githubusercontent.com/836867/182871763-de2e7931-05db-4636-a346-aec8b06175c2.png)

**Comment by Romangelo** [comment]
Are you sure it supposed to work? I tried so many cookies, logged out and logged in several times to get new cookies. None of them work.

**Comment by Nandaka** [comment]
Is your user agent also matching with the browser you use?
![image](https://user-images.githubusercontent.com/836867/182980695-ac68f3e1-2332-470a-a54b-55511ddf5f70.png)

**Comment by Romangelo** [comment]
Mine says:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

How do I set it up properly? Your Chrome seems to be different as it says Chrome/87.0.

**Comment by Nandaka** [comment]
when you copy the cookies, also copy the user agent.

![image](https://user-images.githubusercontent.com/836867/183031819-47a627b7-d97d-411b-9797-e01a50237d72.png)

**Comment by Romangelo** [comment]
I updated that. Still having the problem.

**Comment by Nandaka** [comment]
weird, even without cookie, I still can get the images (just limited to 20 page from server side limit).
Can you upload the log file here, should be named like `log-2022-08-05.txt` in the same folder.

Also, not sure is you need to set the language to English or not.

**Comment by Romangelo** [comment]
`2022-08-05 16:11:20,406 INFO  - Logging Enabled
2022-08-05 16:11:20,680 INFO  - Starting up Danbooru Downloader 3.2022.08.04
2022-08-05 16:11:20,683 DEBUG - Loading provider list.
2022-08-05 16:11:20,721 DEBUG - Provider list loaded.
2022-08-05 16:11:20,727 DEBUG - Danbooru Downloader 3.2022.08.04 loaded.
2022-08-05 16:11:51,759 INFO  - [DoBatchJob] Processing Batch Job#0
2022-08-05 16:11:51,780 INFO  - [DoBatchJob] Downloading list: https://chan.sankakucomplex.com/?tags=samneco&commit=Search
2022-08-05 16:11:56,121 INFO  - [DoBatchJob] Getting file_url from https://chan.sankakucomplex.com/post/show/31356074
2022-08-05 16:11:57,016 ERROR - [DoBatchJob] Error Resolving FileUrl (1 of 1): Input string was not in a correct format. ==> Wait for 30s.
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at DanbooruDownloader3.Engine.SankakuComplexParser.ReparseTags(DanbooruPost post, HtmlDocument doc) in D:\UserData\Dropbox\DanbooruDownloader3\DanbooruDownloader3\DanbooruDownloader3\Engine\SankakuComplexParser.cs:line 185
   at DanbooruDownloader3.Engine.SankakuComplexParser.ParsePost(DanbooruPost post, String postHtml, Boolean overideTagParsing) in D:\UserData\Dropbox\DanbooruDownloader3\DanbooruDownloader3\DanbooruDownloader3\Engine\SankakuComplexParser.cs:line 120
   at DanbooruDownloader3.FormMain.ResolveFileUrlBatch(ExtendedWebClient _clientPost, DanbooruPost post) in D:\UserData\Dropbox\DanbooruDownloader3\DanbooruDownloader3\DanbooruDownloader3\FormMain.cs:line 1410
2022-08-05 16:12:27,333 INFO  - [DoBatchJob] Retrying...
2022-08-05 16:12:27,335 INFO  - [DoBatchJob] Download skipped, ID: 31356074 ==> No file_url, probably deleted`

It's kinda weird. Seems like the program pointing to something at "D:\UserData\... while I don't even have that directory path on my system. Is that something on your PC?

**Comment by Nandaka** [comment]
fyi, if your cookies contains `blacklisted_tags=`, ensure the `&` is changed to to `&amp;` if you modify using notepad. e.g. `blacklisted_tags=censored&amp;yaoi&amp;furry&amp;trap;`

**Comment by Nandaka** [comment]
> about the path

weird, it is the source code location. I think it is because .pdb file also attached in the zip file.

**Comment by Romangelo** [comment]
Even a freshly extracted program, with nothing modified, no cookie. It doesn't work at all for Sankaku.

**Comment by Romangelo** [comment]
This is one of the dump files that were created for every file that failed to download.

https://mega.nz/file/oltjASaS#RBnC7P44rYYfujLC7NGEFZVbVAzGjHq9E4SjBuyFoZo

**Comment by Nandaka** [comment]
ok, found out the issue. Looks like it failed to parse the tag count.

**Comment by Nandaka** [comment]
can you try https://github.com/Nandaka/DanbooruDownloader/releases/tag/v3.20220806

**Comment by Romangelo** [comment]
So far so good. It works.

I'll report back if I find any issues.
