### ISSUE TITLE
Sankaku no longer work (2023-12)

### ISSUE THREAD

**Issue by Romangelo** [Nandaka/DanbooruDownloader#290]
They updated their website again. Most tags I tried to download in Full Batch Mode gave errors.

> [DoBatchJob] Processing Batch Job#1
[DoBatchJob] Downloading list: https://chan.sankakucomplex.com/?tags=samneco+date:b2023-01-01..2023-12-31&commit=Search
[DoBatchJob] Error: System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at DanbooruDownloader3.Engine.SankakuComplexParser.Parse(String data, DanbooruSearchParam searchParam)
   at DanbooruDownloader3.DAO.DanbooruPostDao..ctor(Stream input, DanbooruPostDaoOption option, Nullable`1 currentPage)
   at DanbooruDownloader3.FormMain.GetBatchImageList(DanbooruBatchJob job, Nullable`1 currPage, Nullable`1& status)
   at DanbooruDownloader3.FormMain.DoBatchJob(BindingList`1 jobs)

**Comment by jkaryan** [comment]
Same issue here.

**Comment by Nandaka** [comment]
on it
